### ISSUE TITLE
request.Content Headers dropped

### ISSUE THREAD

**Issue by metalfork** [tsibelman/aws-signer-v4-dot-net#16]
All request.Content.Headers are lost when signing a request. Specifically seeing this with Content-Type.

**Comment by ronenfe** [comment]
Thank you for the info, I'm fixing it.

**Comment by ronenfe** [comment]
In the meantime you can use version 0.77. A fixed version will be published soon.

**Comment by ronenfe** [comment]
Fixed, please update to latest Nuget.
