### ISSUE TITLE
AWS4 RequestSigner does not contain a constructor that takes 3 arguments

### ISSUE THREAD

**Issue by sledgimp** [tsibelman/aws-signer-v4-dot-net#17]
According to the pull request for passing a token in addition to the Key and Secret you have added this functionality. I am getting this error from the following code line.
AWS4RequestSigner l_signer = new AWS4RequestSigner(m_sKey, m_sSecret, m_sToken);

**Comment by tsibelman** [comment]
I guess your dll is not updated try deleting it
