### ISSUE TITLE
Issue for create signing request for query pram

### ISSUE THREAD

**Issue by DeepSinha123** [tsibelman/aws-signer-v4-dot-net#2]
I have a problem while requesting  "**https://example.com/users/{userId}/charities/findByCharityName?offset=20&searchTerm=red wing**"

it's responding me as "**The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.**"

even I am converting searchTerm to Uri.EscapeDataString(searchTerm).

Can you please help me to resolve this issue.

Thank You....

**Comment by tsibelman** [comment]
I sean this happened when you modify request after it was signed.  For example, if some header added after the signing.
