### ISSUE TITLE
Always return forbidden

### ISSUE THREAD

**Issue by EliasHLl** [tsibelman/aws-signer-v4-dot-net#24]
Hi,
First of all thanks for your time and acknowledgment.
I clone your solution to test my aws account but always return 403.
However, if I try the same with a java solution they run correctly.

Can you test and certificate than the code run correctly and the problem is my?

Thanks!

**Comment by tsibelman** [comment]
We using this nugget in production so it working for us. If you post a sample of your code I can take a look.
