### ISSUE TITLE
working example?

### ISSUE THREAD

**Issue by smithburger** [tsibelman/aws-signer-v4-dot-net#27]
New to github so sorry if this is the wrong place to ask. I am pretty confused with AWS singing and I have to talk to one of their new APIs without any previous experience. Do you have a working example showing a full simple get request using your library to sign it?

**Comment by tsibelman** [comment]
If you want to call AWS services API the best approach would be using their SDK, this library useful if you need to call your own services behind API Gateway

**Comment by smithburger** [comment]
There is no SDK for the service I need to connect with yet and I don't suspect there will be for a while. FWIW I am trying to connect to the Direct Fulfillment API which is brand new. Has only been out a couple months total. I will keep looking. Thank you for your time and all the best!

**Comment by ronenfe** [comment]
There is an example in the main page: https://github.com/tsibelman/aws-signer-v4-dot-net
