### ISSUE TITLE
I have a deadlock issue, when multiple threads try to call the .Sign() method, what could be the issue?

### ISSUE THREAD

**Issue by ltoshev** [tsibelman/aws-signer-v4-dot-net#32]
I don't see any locking code inside the sign method?

**Comment by tsibelman** [comment]
Most likely you trying to use it from non asyn code it will happen any time you sync over async

**Comment by ronenfe** [comment]
we are fixing now a deadlock issue when asp.net web forms is calling the signing and gets into deadlock. This should work in the version 1.0.4, please retest.
