### ISSUE TITLE
.Net Core compatibility

### ISSUE THREAD

**Issue by rogermule** [tsibelman/aws-signer-v4-dot-net#35]
Is this library compatible with .Net Core? And what is the minimum .Net framework that is supported?

**Comment by tsibelman** [comment]
The library is working with netstandard2.0, you can check this for more info https://docs.microsoft.com/en-us/dotnet/standard/net-standard

**Comment by ronenfe** [comment]
I think it should work with all versions of .net core since 2.0 and all versions of .net framework since version 4.5.
You can see in the nuget page the list of all supported versions:
https://www.nuget.org/packages/Aws4RequestSigner/#supportedframeworks-tab
