### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jwiater** [tsibelman/aws-signer-v4-dot-net#7]
I recommend escaping the querystring[key] in your GetCanonicalQueryParams method
 like:

var queryParams = keys.Select( key => $"{key}={**Uri.EscapeDataString( querystring[key] )**}" );

This will help avoiding problems with some character encoding like space which can be + or %20.
This has caused issues in my case

**Comment by tsibelman** [comment]
Thank you I published 0.4.0 version
