### ISSUE TITLE
Suggestion for dealing with spaces in url

### ISSUE THREAD

**Issue by jwiater** [tsibelman/aws-signer-v4-dot-net#8]
Hi

I found another thing
If there is a space in the url itself, not just the query string we have the same problem.

If the url contains space, normally it is encoded to + or %20
But then it is encoded again with the % to %25 so the %20 becomes %2520

AWS complains about that – the message that “the canonical string should be …”

The solution is to Escape also the URL, but one must be careful since it wants to encode also the  / characters:

So:

In the place where you have:

canonical_request.Append( request.RequestUri.AbsolutePath + "\n" );

use this:

string sanitizedUrl = SanitizeUrl( request.RequestUri.AbsolutePath );
canonical_request.Append( sanitizedUrl + "\n" );

and add SanitizeUrl method:

private string SanitizeUrl( string absolutePath )
{
	StringBuilder sb = new StringBuilder();
	string[] segments = absolutePath.Split( new char[] { '/' }, StringSplitOptions.RemoveEmptyEntries );

	foreach( var s in segments )
	{
		sb.Append( "/" );
		sb.Append( Uri.EscapeDataString( s ) );
	}

	return sb.ToString();
}

Thank you

**Comment by tsibelman** [comment]
Can you give me an example url

**Comment by jwiater** [comment]
imagine passing parameters in url path, not query string:

htttp://someservice/someGetRequest/resourceType/nice**%20**things

Something like that would fail

**Comment by jwiater** [comment]
![image](https://user-images.githubusercontent.com/39766134/52125584-408ee080-262d-11e9-9417-a55a51eb7ee1.png)

Example of API Gateway service using path parameters

**Comment by tsibelman** [comment]
I made a new version with this change.
